server:
  port: 8080
spring:
  application:
    name: "ms_furniture"
  devtools:
    add-properties: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  queue: "event.stats.validated"
management:
  endpoints:
    web:
      base-path: "/api/v1"
      path-mapping:
        health: "health"
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: us-east-1
  dynamodb:
    endpoint: "http://dynamodb-local:8000"
    table-name: "Stats"